web-padawan/vanilla-colorful

src/color-picker-hex.ts
src/color-picker-hsl-string.ts
src/color-picker-hsl.ts
src/color-picker-hsv.ts
src/color-picker-rgb-string.ts
src/color-picker-rgb.ts
src/hex-input.ts
src/lib/entrypoints/hex-input.ts
src/lib/entrypoints/hex.ts
src/lib/entrypoints/hsl-string.ts
src/lib/entrypoints/hsl.ts
src/lib/entrypoints/hsv.ts
src/lib/entrypoints/rgb-string.ts
src/lib/entrypoints/rgb.ts

Fixes #1 
From now on, it will be possible to import base classes, extend them and register custom elements.
Note that internal elements (`color-hue` and `color-saturation`) are still registered. 
I think we could at least use a different prefix, e.g. `vc-` ("vanilla-colorful") for those.

feat: add base classes entrypoints

---

.gitignore
README.md
demo/index.html
demo/styles.css
package.json
src/hex-color-picker.ts
src/hsl-color-picker.ts
src/hsl-string-color-picker.ts
src/hsv-color-picker.ts
src/lib/components/color-picker.ts
src/lib/components/saturation.ts
src/lib/entrypoints/hsl.ts
src/lib/entrypoints/hsv.ts
src/lib/entrypoints/rgb.ts
src/lib/types.ts
src/lib/utils/compare.ts
src/lib/utils/convert.ts
src/rgb-color-picker.ts
src/rgb-string-color-picker.ts
src/test/color-picker.test.ts
src/test/hex-input.test.ts

Changing the tag names in order to make the type of the specific element in markup more easily discoverable.

refactor!: rename components and types

---

README.md
src/hex-input.ts
src/lib/entrypoints/hex-input.ts
src/test/hex-input.test.ts

This is a breaking change which prevents the `hex-input` from attaching an `input` to its own light DOM.
Instead the `<slot>` with a fallback content is used, with a `slotchange` event listener to handle custom input.

refactor!: use Shadow DOM in hex-input

---

package.json

when respecting the exports field all entry points need to be in it 😅
I wanted to use the `hex-color-picker.js` but it was missing so I added it

fix: add hex-color-picker export

---

package.json
src/lib/components/alpha-color-picker.ts
src/lib/components/alpha.ts
src/lib/components/color-picker.ts
src/lib/components/hue.ts
src/lib/components/saturation.ts
src/lib/components/slider.ts
web-test-runner.config.js

Now when we use plain classes and not internal elements, some logic can be simplified.

refactor: cleanup private methods

---

src/hsla-color-picker.ts
src/hsla-string-color-picker.ts
src/hsva-color-picker.ts
src/hsva-string-color-picker.ts
src/lib/components/alpha.ts
src/lib/components/hue.ts
src/lib/components/saturation.ts
src/lib/components/slider.ts
src/lib/styles/alpha.scss
src/lib/styles/color-picker.scss
src/rgba-color-picker.ts
src/rgba-string-color-picker.ts

Removed extra gradient part, which allowed to simplify slider templates even more.

refactor: use pseudo-element for gradient

---

src/lib/entrypoints/hex-input.ts
src/lib/entrypoints/hex.ts
src/lib/entrypoints/hsl-string.ts
src/lib/entrypoints/hsl.ts
src/lib/entrypoints/hsla-string.ts
src/lib/entrypoints/hsla.ts
src/lib/entrypoints/hsv-string.ts
src/lib/entrypoints/hsv.ts
src/lib/entrypoints/hsva-string.ts
src/lib/entrypoints/hsva.ts
src/lib/entrypoints/rgb-string.ts
src/lib/entrypoints/rgb.ts
src/lib/entrypoints/rgba-string.ts
src/lib/entrypoints/rgba.ts
src/lib/types.ts

This change makes it possible to get following benefits when using TypeScript:
1. `color-changed` event name is listed in the event names autocomplete,
2. `event` parameter type is inferred based on the color-picker tag name.

feat: add color-changed event typings

---

package.json

We don't use internal custom elements anymore, so only the entrypoints with `customElements.define` contain side effects.

chore: add sideEffects to package.json

---

src/lib/components/color-picker.ts
src/test/color-picker.test.ts

This is a breaking change aiming to align the implementation with [Custom Elements best practices](https://web.dev/custom-elements-best-practices/#events):
> Dispatching an event in response to a host setting a property is superfluous (the host knows the current state because it just set it). Dispatching events in response to a host setting a property may cause infinite loops with data binding systems.
From now on, `color-changed` event is only fired when color is picked by the user.
It will NOT be fired on setting `color` as a property or attribute on the component.
Fixes #64
Closes #70

refactor!: do not fire event on setting color

---

package.json
src/lib/styles/color-picker.css

Fixes #57
Changed to use `display: flex` instead of `position: absolute` - inspired by https://github.com/omgovich/react-colorful/pull/175

fix: center pointer fill using flexbox

---

.gitignore
package.json
scripts/build-web-types.cjs

Add support for the [Web-Types standard](https://github.com/JetBrains/web-types) for documenting web component libraries used by IntelliJ.
This adds auto-complete support for all included components when using them in HTML or Lit templates:

feat: add Web Types support for IntelliJ

---

README.md

Added an example of importing the component from https://esm.sh which is a yet another ESM friendly CDN.

chore: add esm.sh CDN example to README

---

.github/workflows/tests.yml

- Updated `actions/checkout` and `actions/setup-node` to latest
- Updated Node.js version to 16 (will switch to 18 later this year)

chore: bump GitHub Actions and Node versions

---

README.md

1. Updated and clarified ES modules section, added links to import maps spec and browser support
2. Removed mention of Snowpack as it's no longer maintained and not recommended for new projects
3. Also fixed a small typo in the features table: `straight forward` -> `straightforward`

chore: update and clarify ES modules section

---

src/test/color-picker.test.ts

Moved `rgba-color-picker` tests to own suite, instead of having them under `hex-color-picker` suite.

test: move rgba-color-picker tests to own suite

---

src/lib/entrypoints/hex-input.ts
src/lib/utils/convert.ts

Same as https://github.com/omgovich/react-colorful/pull/182
Removed the `substr` method usage, as it's deprecated:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

refactor: use substring instead of substr

---

README.md
src/hex-input.ts
src/lib/entrypoints/hex-input.ts
src/lib/utils/validate.ts
src/test/hex-input.test.ts

Added support for `alpha` property / attribute to `<hex-input>`, based on the commit from #81.
See also https://github.com/omgovich/react-colorful/pull/155 where this feature has been originally implemented.

feat: add support for alpha to hex-input

---

README.md
package.json
src/hex-input.ts
src/lib/entrypoints/hex-input.ts
src/test/hex-input.test.ts

Added `prefixed` property to`<hex-input>` that enables displaying `#` prefix in the `<input>`.
See also https://github.com/omgovich/react-colorful/pull/146 where this has been originally implemented.

feat: add prefixed property to hex-input

---

src/lib/entrypoints/hex-input.ts
src/test/hex-input.test.ts

1. Moved `attachShadow()` call to the `hex-input` constructor to not throw on re-attach,
2. Fixed `slotchange` listener to set value on the custom `<input>` when adding it lazily.

fix: handle reattach and changing input

---

package.json
src/lib/components/color-picker.ts
src/lib/components/slider.ts
src/lib/entrypoints/hex-input.ts
src/lib/utils/dom.ts

Changed the helper used to render the template content, which causes the following bundle size reduction:
```diff
hex-alpha-color-picker.js
Size limit: 3.15 kB
-  Size:       3.12 kB with all dependencies, minified and gzipped
+  Size:       3.11 kB with all dependencies, minified and gzipped
hex-color-picker.js
Size limit: 2.8 kB
-  Size:       2.8 kB with all dependencies, minified and gzipped
+  Size:       2.79 kB with all dependencies, minified and gzipped 
hsl-color-picker.js
Size limit: 2.5 kB
-  Size:       2.45 kB with all dependencies, minified and gzipped
+  Size:       2.44 kB with all dependencies, minified and gzipped
hsl-string-color-picker.js
Size limit: 2.7 kB
-  Size:       2.62 kB with all dependencies, minified and gzipped
+  Size:       2.6 kB with all dependencies, …
```

refactor: simplify render helper to reduce size

---

src/lib/styles/color-picker.css

Prefixed properties are supposed to be followed by unprefixed properties to ensure that modern browsers use the most relevant and standard-compliant implementation if they still support both. I understand that it’s not super relevant, but just for the sake of spreading the knowledge, I’ll give it a go :)
For more details on the matter, see Eric Meyer’s [Prefix or Posthack](https://alistapart.com/article/prefix-or-posthack/#section6) article. Oh my, it’s 14 years old!

Move prefixed properties before unprefixed
