src/lib/components/color-picker.ts, src/test/color-picker.test.ts
Also removed usage of `Symbol` for private fields to save few bytes.
=> fix: only fire event if color changes

package-lock.json, package.json, src/lib/components/interactive.ts, src/test/color-picker.test.ts
Inspired by https://github.com/omgovich/react-colorful/pull/56
=> Ignore mouse events on touch devices

README.md
=> docs: add color property to example

README.md, package.json, src/lib/components/alpha.ts, src/lib/components/hue.ts, src/lib/components/interactive.ts, src/lib/components/saturation.ts, src/lib/styles/interactive.scss, src/test/a11y.test.ts, web-test-runner.config.js
=> Implement accessibility support

README.md
=> docs: document bare module imports

src/lib/components/color-picker.ts, src/lib/entrypoints/hex-input.ts, src/test/color-picker.test.ts
=> fix: make color-changed event bubble

src/lib/components/alpha-color-picker.ts, src/lib/components/alpha.ts, src/lib/components/color-picker.ts, src/lib/components/hue.ts, src/lib/components/saturation.ts, src/lib/components/slider.ts, src/lib/entrypoints/hex-input.ts, src/lib/utils/dom.ts
Updated the base class to create a single `<style>` element per component.
=> refactor: place CSS in single style tag

src/lib/components/color-picker.ts, src/test/color-picker.test.ts
=> fix: prevent hue from being reset

package.json, src/lib/utils/convert.ts, src/test/utils.test.ts
Port of https://github.com/omgovich/react-colorful/pull/133
=> feat: support modern CSS color notations

README.md
Aligned the emojis with `react-colorful` too 🙂
=> chore: make features section look fancy

README.md
- changed Features to use regular spaces (the large ones don't look nice on mobile)
- updated Lit example to use the new demo from Lit playground
=> chore: minor updates to README

src/lib/styles/alpha.css, src/lib/styles/color-picker.css, src/lib/styles/hue.css, src/lib/styles/saturation.css
Now when we have more simple DOM structure, some styles are no longer needed. Also there were some duplicates.
=> refactor: remove no longer needed CSS

src/lib/styles/saturation.css
Port of https://github.com/omgovich/react-colorful/pull/140
=> fix: resolve rounded corner rendering bug

src/lib/components/slider.ts, src/test/color-picker.test.ts
Related to https://github.com/omgovich/react-colorful/pull/143
=> fix: focus the slider on mousedown

package-lock.json, package.json
1. Replaced `web-components-analyzer` with the latest version of `@custom-elements-manifest/analyzer`.
2. Also added `customElements` entry to `package.json` as some tools could potentially benefit from it.
=> feat: use Custom Elements Manifest analyzer

src/lib/entrypoints/hex-input.ts, src/test/hex-input.test.ts
=> fix: do not restore value after clearing

src/hex-input.ts
Updated the description which appears to be a copy-paste from `hex-color-picker`.
=> docs: update hex-input JSDoc description

README.md, src/test/utils.test.ts, web-test-runner.config.js
Added some missing tests for color utils to get 100% test coverage.
=> test: add missing tests to get 100% coverage

src/test/color-picker.test.ts
Updated a unit test to remove extra element reference and align with other tests.
=> test: cleanup extra element reference in test

package-lock.json, package.json
Added `prettier-plugin-package` and formatted `package.json` with Prettier.
=> chore: format package.json with Prettier

.github/workflows/tests.yml, .gitignore, package-lock.json, package.json, src/lib/components/alpha.ts
Changed npm scripts to use [`wireit`](https://github.com/google/wireit) for better developer experience.
=> chore: use wireit for managing npm scripts

index.html
Added the Mastodon verification link to be placed on the demo page.
=> chore: add Mastodon profile link to demo page
